package com.example.miniprogramme_springboot.dao;

import com.example.miniprogramme_springboot.domain.Receiveinfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReceiveinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiveinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiveinfo
     *
     * @mbggenerated
     */
    int insert(Receiveinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiveinfo
     *
     * @mbggenerated
     */
    int insertSelective(Receiveinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiveinfo
     *
     * @mbggenerated
     */
    Receiveinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiveinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Receiveinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiveinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Receiveinfo record);

    List getReceiveinfoByUid(int uid);

    Integer updateReceiveinfo(@Param(value = "id") Integer rid, @Param(value = "name") String name,@Param(value = "tel") String tel,@Param(value = "address") String address, @Param(value = "ischoosed") Boolean ischoose);
}