package com.example.miniprogramme_springboot.dao;

import com.example.miniprogramme_springboot.domain.Shoppingcar;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ShoppingcarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbggenerated
     */
    int insert(Shoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbggenerated
     */
    int insertSelective(Shoppingcar record);

    List getshoppingcar();
    Integer getrecommendBook(@Param(value = "simList")Map<Integer, Double> simList);

//    List recommendBook();
}