package com.example.miniprogramme_springboot.domain;

import java.util.Date;

public class History {
   private Books books;

    public Books getBooks() {
        return books;
    }

    public void setBooks(Books books) {
        this.books = books;
    }

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.b_id
     *
     * @mbggenerated
     */
    private Integer bId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.u_id
     *
     * @return the value of history.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.u_id
     *
     * @param uId the value for history.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.b_id
     *
     * @return the value of history.b_id
     *
     * @mbggenerated
     */
    public Integer getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.b_id
     *
     * @param bId the value for history.b_id
     *
     * @mbggenerated
     */
    public void setbId(Integer bId) {
        this.bId = bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.time
     *
     * @return the value of history.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.time
     *
     * @param time the value for history.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}