package com.example.miniprogramme_springboot.domain;

public class Rating {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.b_id
     *
     * @mbggenerated
     */
    private Integer bId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.rating
     *
     * @mbggenerated
     */
    private Integer rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.is_like
     *
     * @mbggenerated
     */
    private Boolean isLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.id
     *
     * @return the value of rating.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.id
     *
     * @param id the value for rating.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.u_id
     *
     * @return the value of rating.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.u_id
     *
     * @param uId the value for rating.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.b_id
     *
     * @return the value of rating.b_id
     *
     * @mbggenerated
     */
    public Integer getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.b_id
     *
     * @param bId the value for rating.b_id
     *
     * @mbggenerated
     */
    public void setbId(Integer bId) {
        this.bId = bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.rating
     *
     * @return the value of rating.rating
     *
     * @mbggenerated
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.rating
     *
     * @param rating the value for rating.rating
     *
     * @mbggenerated
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.is_like
     *
     * @return the value of rating.is_like
     *
     * @mbggenerated
     */
    public Boolean getIsLike() {
        return isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.is_like
     *
     * @param isLike the value for rating.is_like
     *
     * @mbggenerated
     */
    public void setIsLike(Boolean isLike) {
        this.isLike = isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.comments
     *
     * @return the value of rating.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.comments
     *
     * @param comments the value for rating.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}