package com.example.miniprogramme_springboot.domain;

public class Receiveinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiveinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiveinfo.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiveinfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiveinfo.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiveinfo.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiveinfo.ischoosed
     *
     * @mbggenerated
     */
    private Boolean ischoosed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiveinfo.id
     *
     * @return the value of receiveinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiveinfo.id
     *
     * @param id the value for receiveinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiveinfo.u_id
     *
     * @return the value of receiveinfo.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiveinfo.u_id
     *
     * @param uId the value for receiveinfo.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiveinfo.name
     *
     * @return the value of receiveinfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiveinfo.name
     *
     * @param name the value for receiveinfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiveinfo.address
     *
     * @return the value of receiveinfo.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiveinfo.address
     *
     * @param address the value for receiveinfo.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiveinfo.tel
     *
     * @return the value of receiveinfo.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiveinfo.tel
     *
     * @param tel the value for receiveinfo.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiveinfo.ischoosed
     *
     * @return the value of receiveinfo.ischoosed
     *
     * @mbggenerated
     */
    public Boolean getIschoosed() {
        return ischoosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiveinfo.ischoosed
     *
     * @param ischoosed the value for receiveinfo.ischoosed
     *
     * @mbggenerated
     */
    public void setIschoosed(Boolean ischoosed) {
        this.ischoosed = ischoosed;
    }
}